package Ranex.ruvo.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "delivery_partners")
public class DeliveryPartner {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false, unique = true)
    private String userId;

    /** Central identity for this rider; the legacy userId is retained for existing assignments. */
    @Column(name = "auth_identity_id", unique = true)
    private Long authIdentityId;

    @Column(name = "shop_id")
    private Long shopId; // Null means they are a general RuVo partner

    @Column(nullable = false)
    private String name;

    @Column(nullable = false, unique = true)
    private String phone;

    private Double latitude;

    private Double longitude;

    @Column(name = "location_name")
    private String locationName;

    @Column(name = "last_active_at")
    private java.time.Instant lastActiveAt;

    @Builder.Default
    @Column(nullable = false)
    private Boolean active = true;

    @Builder.Default
    @Column(nullable = false)
    private Boolean available = false; // Toggled by partner apps

    @Builder.Default
    @Column(nullable = false)
    private Boolean approved = false; // Approved by admin

    // Aadhaar Verification & Document Photos
    @Column(name = "aadhaar_number")
    private String aadhaarNumber;

    @Column(name = "aadhaar_name")
    private String aadhaarName;

    @Column(name = "aadhaar_front_url")
    private String aadhaarFrontUrl;

    @Column(name = "aadhaar_back_url")
    private String aadhaarBackUrl;

    @Builder.Default
    @Column(name = "aadhaar_verified")
    private Boolean aadhaarVerified = false;

    // Bank Account Details for Delivery Fee Settlement
    @Column(name = "bank_account_number")
    private String bankAccountNumber;

    @Column(name = "ifsc_code")
    private String ifscCode;

    @Column(name = "bank_name")
    private String bankName;

    @Column(name = "bank_account_holder")
    private String bankAccountHolder;

    @Column(name = "upi_id")
    private String upiId;

    /**
     * UNVERIFIED, VERIFIED, REJECTED, PENDING
     */
    @Builder.Default
    @Column(name = "bank_verification_status", length = 50)
    private String bankVerificationStatus = "UNVERIFIED";

    // Razorpay linked account ID for instant delivery-fee split
    // Generated by Razorpay when partner is registered as a linked account
    @Column(name = "razorpay_account_id")
    private String razorpayAccountId;

    /** Comma-separated list of shop IDs selected by delivery partner during onboarding/settings */
    @Column(name = "preferred_shop_ids", length = 1000)
    private String preferredShopIds;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) createdAt = Instant.now();
        if (bankVerificationStatus == null) bankVerificationStatus = "UNVERIFIED";
        if (approved == null) approved = false;
        if (active == null) active = true;
        if (available == null) available = false;
    }
}
