package Ranex.ruvo.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "delivery_partners")
public class DeliveryPartner {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false, unique = true)
    private String userId;

    /** Central identity for this rider; the legacy userId is retained for existing assignments. */
    @Column(name = "auth_identity_id", unique = true)
    private Long authIdentityId;

    @Column(name = "shop_id")
    private Long shopId; // Null means they are a general RuVo partner

    @Column(nullable = false)
    private String name;

    @Column(nullable = false, unique = true)
    private String phone;

    private Double latitude;

    private Double longitude;

    @Column(name = "location_name")
    private String locationName;

    @Column(name = "last_active_at")
    private java.time.Instant lastActiveAt;

    @Builder.Default
    @Column(nullable = false)
    private Boolean active = true;

    @Builder.Default
    @Column(nullable = false)
    private Boolean available = false; // Toggled by partner apps

    @Builder.Default
    @Column(nullable = false)
    private Boolean approved = false; // Approved by admin

    // Cashfree vendor/sub-merchant ID for instant delivery-fee split
    // Generated by Cashfree when partner is registered as a vendor
    @Column(name = "cashfree_vendor_id")
    private String cashfreeVendorId;

    /** Comma-separated list of shop IDs selected by delivery partner during onboarding/settings */
    @Column(name = "preferred_shop_ids", length = 1000)
    private String preferredShopIds;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
    }
}
