package Ranex.ruvo.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "shops")
public class Shop {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String category;

    @Column(name = "banner_url")
    private String bannerUrl;

    @Column(name = "logo_url")
    private String logoUrl;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "shop_images", joinColumns = @JoinColumn(name = "shop_id"))
    @Column(name = "image_url")
    @Builder.Default
    private java.util.List<String> images = new java.util.ArrayList<>();

    private String address;

    // Display name for the shop owner (kept for backwards compatibility)
    private String owner;

    // Actual user id of the account that registered the shop — used to look up
    // "my shops" regardless of approval status. Should match AuthToken.userId.
    @Column(name = "owner_id")
    private String ownerId;

    /** Central identity owning this shop. Legacy ownerId remains during migration. */
    @Column(name = "auth_identity_id")
    private Long authIdentityId;

    private String phone;

    private Double rating;

    @Column(name = "delivery_available")
    private Boolean deliveryAvailable;

    // For Nearby Location
    private Double latitude;
    private Double longitude;

    @Column(name = "opening_time")
    private LocalTime openingTime;

    @Column(name = "closing_time")
    private LocalTime closingTime;

    @Builder.Default
    @Column(name = "approved")
    private Boolean approved = false;

    @Builder.Default
    @Column(name = "active")
    private Boolean active = true;

    // Split Payment Settlement Details
    @Column(name = "upi_id")
    private String upiId;

    @Column(name = "bank_account_number")
    private String bankAccountNumber;

    @Column(name = "ifsc_code")
    private String ifscCode;

    // Generated by Cashfree when registered as a vendor
    @Column(name = "cashfree_vendor_id")
    private String cashfreeVendorId;

    @Builder.Default
    @Column(name = "settlement_blocked", nullable = false)
    private Boolean settlementBlocked = false;

    @Builder.Default
    @Column(name = "cod_blocked", nullable = false)
    private Boolean codBlocked = false;
}
