package Ranex.ruvo.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "shops")
public class Shop {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String category;

    @Column(name = "banner_url")
    private String bannerUrl;

    @Column(name = "logo_url")
    private String logoUrl;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "shop_images", joinColumns = @JoinColumn(name = "shop_id"))
    @Column(name = "image_url")
    @Builder.Default
    private java.util.List<String> images = new java.util.ArrayList<>();

    private String address;

    // Display name for the shop owner (kept for backwards compatibility)
    private String owner;
    
    // Contact email for the shop / owner
    private String email;

    // Actual user id of the account that registered the shop — used to look up
    // "my shops" regardless of approval status. Should match AuthToken.userId.
    @Column(name = "owner_id")
    private String ownerId;

    /** Central identity owning this shop. Legacy ownerId remains during migration. */
    @Column(name = "auth_identity_id")
    private Long authIdentityId;

    private String phone;

    private Double rating;

    @Column(name = "delivery_available")
    private Boolean deliveryAvailable;

    // For Nearby Location
    private Double latitude;
    private Double longitude;

    @Column(name = "opening_time")
    private LocalTime openingTime;

    @Column(name = "closing_time")
    private LocalTime closingTime;

    @Builder.Default
    @Column(name = "approved")
    private Boolean approved = false;

    @Builder.Default
    @Column(name = "active")
    private Boolean active = true;

    // Aadhaar Verification & Documents
    @Column(name = "aadhaar_number")
    private String aadhaarNumber;

    @Column(name = "aadhaar_name")
    private String aadhaarName;

    @Column(name = "aadhaar_front_url")
    private String aadhaarFrontUrl;

    @Column(name = "aadhaar_back_url")
    private String aadhaarBackUrl;

    @Builder.Default
    @Column(name = "aadhaar_verified")
    private Boolean aadhaarVerified = false;

    // Split Payment Settlement Details
    @Column(name = "upi_id")
    private String upiId;
    @Column(name = "bank_account_number")
    private String bankAccountNumber;

    @Column(name = "bank_name")
    private String bankName;

    @Column(name = "bank_account_holder")
    private String bankAccountHolder;

    @Column(name = "ifsc_code")
    private String ifscCode;

    /**
     * UNVERIFIED, VERIFIED, REJECTED, PENDING
     */
    @Builder.Default
    @Column(name = "bank_verification_status", length = 50)
    private String bankVerificationStatus = "UNVERIFIED";

    // Generated by Razorpay when registered as a vendor/linked account
    @Column(name = "razorpay_account_id")
    private String razorpayAccountId;

    @Builder.Default
    @Column(name = "settlement_blocked", nullable = false)
    private Boolean settlementBlocked = false;

    @Builder.Default
    @Column(name = "cod_blocked", nullable = false)
    private Boolean codBlocked = false;

    @Builder.Default
    @Column(name = "unpaid_platform_fee", precision = 10, scale = 2)
    private java.math.BigDecimal unpaidPlatformFee = java.math.BigDecimal.ZERO;

    @Column(name = "last_cod_platform_fee_settled_at")
    private java.time.LocalDateTime lastCodPlatformFeeSettledAt;

    @Column(name = "oldest_unpaid_cod_at")
    private java.time.LocalDateTime oldestUnpaidCodAt;

    @Builder.Default
    @Column(name = "disabled_due_to_settlement", nullable = false)
    private Boolean disabledDueToSettlement = false;

    @PrePersist
    public void prePersist() {
        if (this.approved == null) this.approved = false;
        if (this.active == null) this.active = true;
        if (this.bankVerificationStatus == null) this.bankVerificationStatus = "UNVERIFIED";
        if (this.settlementBlocked == null) this.settlementBlocked = false;
        if (this.codBlocked == null) this.codBlocked = false;
        if (this.unpaidPlatformFee == null) this.unpaidPlatformFee = java.math.BigDecimal.ZERO;
        if (this.disabledDueToSettlement == null) this.disabledDueToSettlement = false;
    }
}
