package Ranex.ruvo.controller;

import Ranex.ruvo.service.SettlementService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/settlements")
@CrossOrigin(origins = "*")
public class SettlementController {

    private final SettlementService settlementService;

    public SettlementController(SettlementService settlementService) {
        this.settlementService = settlementService;
    }

    // Shopkeeper hits this to generate an OTP so that the Partner can hand over cash.
    @PostMapping("/partner-to-shop/initiate")
    public ResponseEntity<?> initiatePartnerToShop(@RequestParam Long partnerId, @RequestParam Long shopId) {
        try {
            String otp = settlementService.initiatePartnerToShopCodSettlement(partnerId, shopId);
            return ResponseEntity.ok("OTP generated: " + otp);
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    // Partner hits this, inputs the OTP generated by the shopkeeper, and marks COD cash handoff as COMPLETE.
    @PostMapping("/partner-to-shop/verify")
    public ResponseEntity<?> verifyPartnerToShop(@RequestParam Long partnerId, @RequestParam Long shopId, @RequestParam String otp) {
        try {
            settlementService.verifyPartnerToShopCodSettlement(partnerId, shopId, otp);
            return ResponseEntity.ok("COD Cash Handed Over successfully. Shop liabilities updated.");
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }
}
