import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import { api } from '../services/api';
import { Delivery, partnerService } from '../services/partnerService';

export const AvailableDeliveriesScreen = () => {
  const { token } = useAuth(); const { colors } = useTheme(); const navigation = useNavigation<any>();
  const [runs,setRuns]=useState<Delivery[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<number|null>(null); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{if(!token)return; try {setError(null); setRuns(await api<Delivery[]>('/api/partner/deliveries/available',token));} catch(e:any){setError(e.message)} finally {setLoading(false)}},[token]);
  useFocusEffect(useCallback(()=>{load()},[load]));
  const accept=async(run:Delivery)=>{if(!token)return;setBusy(run.id);try{await api(`/api/partner/deliveries/${run.id}/accept`,token,{method:'POST'});navigation.navigate('ActiveDelivery',{deliveryId:run.id});}catch(e:any){Alert.alert('Run unavailable',e.message);load()}finally{setBusy(null)}};
  return <View style={[styles.page,{backgroundColor:colors.background}]}><View style={styles.header}><Text style={[styles.title,{color:colors.textPrimary}]}>Available deliveries</Text><Text style={[styles.subtitle,{color:colors.textSecondary}]}>Only server-assigned runs appear here.</Text></View>
    {loading?<View style={styles.center}><ActivityIndicator size="large" color={colors.primary}/></View>:error?<View style={styles.center}><Ionicons name="cloud-offline-outline" size={48} color={colors.error}/><Text style={[styles.error,{color:colors.textPrimary}]}>{error}</Text><TouchableOpacity onPress={load}><Text style={{color:colors.primary,fontWeight:'700'}}>Try again</Text></TouchableOpacity></View>:<FlatList data={runs} keyExtractor={x=>String(x.id)} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={runs.length?styles.list:styles.empty} ListEmptyComponent={<><Ionicons name="bicycle-outline" size={58} color={colors.border}/><Text style={[styles.emptyTitle,{color:colors.textPrimary}]}>No deliveries right now</Text><Text style={[styles.emptyText,{color:colors.textSecondary}]}>Go online and keep this screen refreshed while waiting for a server assignment.</Text></>} renderItem={({item})=><View style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}><View style={styles.row}><Text style={[styles.order,{color:colors.textPrimary}]}>Order #{item.orderId}</Text><Text style={{color:colors.success,fontWeight:'800'}}>₹{item.deliveryFee}</Text></View><Text style={[styles.address,{color:colors.textSecondary}]} numberOfLines={1}>Pickup: {item.pickupLocation}</Text><Text style={[styles.address,{color:colors.textSecondary}]} numberOfLines={1}>Drop: {item.deliveryLocation}</Text><TouchableOpacity disabled={busy===item.id} onPress={()=>accept(item)} style={[styles.accept,{backgroundColor:colors.primary}]}>{busy===item.id?<ActivityIndicator color="#fff"/>:<Text style={styles.acceptText}>ACCEPT ORDER</Text>}</TouchableOpacity></View>}/>}</View>
};
const styles=StyleSheet.create({page:{flex:1,paddingTop:56},header:{paddingHorizontal:20,paddingBottom:16},title:{fontSize:22,fontWeight:'800'},subtitle:{marginTop:4},center:{flex:1,alignItems:'center',justifyContent:'center',padding:28,gap:14},list:{padding:16,gap:12},empty:{flexGrow:1,alignItems:'center',justifyContent:'center',padding:35},emptyTitle:{fontSize:18,fontWeight:'800',marginTop:16},emptyText:{textAlign:'center',lineHeight:20,marginTop:6},error:{textAlign:'center'},card:{borderWidth:1,borderRadius:16,padding:16,gap:9},row:{flexDirection:'row',justifyContent:'space-between'},order:{fontSize:16,fontWeight:'800'},address:{fontSize:13},accept:{marginTop:5,borderRadius:10,padding:13,alignItems:'center'},acceptText:{color:'#fff',fontWeight:'800'}});
