import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Switch, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import { ApiError } from '../services/api';
import { Delivery, Earnings, partnerService } from '../services/partnerService';

export const DashboardScreen=()=>{
  const {user,token,verificationStatus,refreshProfile}=useAuth();const {colors}=useTheme();const navigation=useNavigation<any>();
  const [online,setOnline]=useState(false);const [earnings,setEarnings]=useState<Earnings|null>(null);const [active,setActive]=useState<Delivery|null>(null);const [loading,setLoading]=useState(true);const [changing,setChanging]=useState(false);
  const load=useCallback(async()=>{if(!token)return;try{const [income,deliveries]=await Promise.all([partnerService.earnings(token),partnerService.activeDeliveries(token)]);setEarnings(income);setActive(deliveries[0]??null);await refreshProfile();}catch{}finally{setLoading(false)}},[token]);
  useFocusEffect(useCallback(()=>{load()},[load]));
  React.useEffect(() => { setOnline(Boolean(user?.isAvailable)); }, [user?.isAvailable]);
  const changeAvailability=async(value:boolean)=>{if(!token)return;if(value&&verificationStatus!=='APPROVED'){Alert.alert('Approval required','Your account must be approved before you can receive deliveries.');return;}if(active&&!value){Alert.alert('Active delivery','Finish or resolve your active delivery before going offline.');return;}setChanging(true);try{await partnerService.availability(token,value);setOnline(value)}catch(e:any){const message=e instanceof ApiError?e.message:'Availability could not be updated.';Alert.alert('Status not changed',message)}finally{setChanging(false)}};
  return <ScrollView style={[styles.page,{backgroundColor:colors.background}]} contentContainerStyle={styles.content}><View style={[styles.hero,{backgroundColor:colors.primary}]}><View><Text style={styles.hello}>Welcome back</Text><Text style={styles.name}>{user?.name || 'Delivery partner'}</Text></View><View style={styles.status}><Text style={styles.statusText}>{online?'ONLINE':'OFFLINE'}</Text><Switch value={online} disabled={changing} onValueChange={changeAvailability} trackColor={{false:'#94a3b8',true:'#22c55e'}} thumbColor="#fff"/></View></View>
    <TouchableOpacity disabled={changing} onPress={()=>changeAvailability(!online)} style={[styles.go,{backgroundColor:online?'#dcfce7':colors.primary,borderColor:online?'#86efac':colors.primary}]}><Ionicons name={online?'radio-button-on':'power'} size={25} color={online?'#15803d':'#fff'}/><Text style={[styles.goText,{color:online?'#15803d':'#fff'}]}>{online?'GO OFFLINE':'GO ONLINE'}</Text></TouchableOpacity>
    {loading?<ActivityIndicator color={colors.primary} style={{margin:32}}/>:<><TouchableOpacity onPress={()=>active&&navigation.navigate('ActiveDelivery',{deliveryId:active.id})} style={[styles.active,{backgroundColor:active?'#fff7ed':colors.card,borderColor:active?'#fdba74':colors.border}]}><Ionicons name={active?'bicycle':'checkmark-circle-outline'} size={30} color={active?'#ea580c':colors.success}/><View style={{flex:1}}><Text style={[styles.cardTitle,{color:colors.textPrimary}]}>{active?'Active delivery':'Ready for your next delivery'}</Text><Text style={{color:colors.textSecondary}}>{active?`Order #${active.orderId} · ${active.status.replaceAll('_',' ')}`:'Go online to receive eligible assignments.'}</Text></View>{active&&<Ionicons name="chevron-forward" size={22} color={colors.textSecondary}/>}</TouchableOpacity>
    <Text style={[styles.section,{color:colors.textPrimary}]}>Earnings</Text><View style={styles.grid}><Metric icon="today-outline" label="Today" value={earnings?.todayEarnings??0} colors={colors}/><Metric icon="wallet-outline" label="Wallet balance" value={earnings?.walletBalance??0} colors={colors}/><Metric icon="trending-up-outline" label="All time" value={earnings?.totalEarnings??0} colors={colors}/></View></>}</ScrollView>
};
const Metric=({icon,label,value,colors}:any)=><View style={[styles.metric,{backgroundColor:colors.card,borderColor:colors.border}]}><Ionicons name={icon} color={colors.primary} size={21}/><Text style={[styles.value,{color:colors.textPrimary}]}>₹{value}</Text><Text style={{color:colors.textSecondary,fontSize:12}}>{label}</Text></View>;
const styles=StyleSheet.create({page:{flex:1},content:{paddingBottom:28},hero:{paddingTop:60,paddingBottom:27,paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between',borderBottomLeftRadius:26,borderBottomRightRadius:26},hello:{color:'#dbeafe',fontSize:14},name:{color:'#fff',fontSize:22,fontWeight:'800',marginTop:2},status:{alignItems:'center'},statusText:{color:'#fff',fontWeight:'800',fontSize:11},go:{margin:20,borderRadius:16,padding:19,alignItems:'center',flexDirection:'row',justifyContent:'center',gap:9,borderWidth:1},goText:{fontSize:17,fontWeight:'900'},active:{marginHorizontal:20,borderWidth:1,borderRadius:16,padding:16,flexDirection:'row',alignItems:'center',gap:12},cardTitle:{fontSize:16,fontWeight:'800',marginBottom:3},section:{fontSize:17,fontWeight:'800',margin:20},grid:{paddingHorizontal:20,flexDirection:'row',gap:10},metric:{flex:1,borderWidth:1,borderRadius:14,padding:12},value:{fontSize:17,fontWeight:'800',marginTop:10,marginBottom:3}});
